"""add phone number

Revision ID: 1340167373ce
Revises: 93d962724497
Create Date: 2024-11-17 23:43:22.813937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1340167373ce'
down_revision: Union[str, None] = '93d962724497'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
   
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
